title: sn00py1310's Blog
description: >-  
  This is my very own blog, but probably I'm the only one reading this. 
  Oh, hey nice to see you :)
author:
  name: sn00py1310

collections_dir: collections
collections:
  posts:
    layout: post
    permalink: /:collection/:year/:month/:day/:title  
    output: true

defaults:
  - scope:
      path: ""
    values:
      image: https://github.com/sn00py1310.png

header_pages:
  - about.md
  - index.md

# Statistics
# google_analytics: G-KKWDB68V2E
plausible:
  src: https://plausible.snoopys.xyz/js/script.outbound-links.js
  domain: blog.snoopys.xyz

# Update version only after testing/reviewing
remote_theme: jekyll/minima
minima:
  skin: auto
  social_links:
    - { platform: github, user_url: "https://github.com/sn00py1310" }

sass:
  style: compressed

# Build Settings
favicon: favicon.ico
timezone: Etc/UTC

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap